apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-spring-boot-gradle
  name: demo-spring-boot-gradle
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-spring-boot-gradle
  type: ClusterIP
status:
  loadBalancer: {}