apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/

replicas:
  - name: demo-spring-boot-gradle
    count: 1

images:
  - name: ghcr.io/leandrosouzabc/demo-spring-boot-gradle
    newTag: v0.5.7